import { Backpack } from "lucide-react-native";

export const theme = {
    colors: {
        primaryorange: "#FFE201",
        secondary: "#00FF00",
        whiteBackground: "#F1F3F9",
        purewhiteBackground:"#FFFFFF",
        whiteText: "#FFFFFF",
        blackBackground:"#191919",
        blackText:"#191919",
        subText:"#666666",
        borderColor:"#E6E6E6",
        borderlightgraycolour:"#F2F2F2",
        orangeColor:"#F2AA2D",
        borderlightorange:"#FFF5F1", 
        lightOrange:"#FEF5F0",
        bordergray:"#E6E6E6",
        textlightgray:"#808080",
        subTextsmall:"#999999",
        graysubtext:"#4D4D4D",
        lightGreen:"#CCFFCC",
        green:"#008000",
        Selectedborder:"#F2AA2D",
        selectedBg:"#FDF1DDC2",
        secondaryOrange:"#FFFEFF",
        primaryorange: "#FF0000",
        secondary: "#00FF00",
        whiteBackground: "#FCFCFC", 
        purewhiteBackground:"#FFFFFF",
        whiteText: "#FFFFFF",
        blackBackground:"#191919",
        blackText:"#191919",
        subText:"#666666",
        borderColor:"#E6E6E6",
        borderlightgraycolour:"#F2F2F2",
        orangeColor:"#F25F17",
        borderlightorange:"#F8C0A0", 
        lightOrange:"#FEF5F0",
        bordergray:"#E6E6E6",
        textlightgray:"#808080",
        subTextsmall:"#999999",
        graysubtext:"#4D4D4D",
        lightGreen:"#CCFFCC",
        green:"#008000",
        Selectedborder:"#FF6666",
        selectedBg:"#FFE5E5",
        secondaryOrange:"#FFFEFF",
        backgroundmaincolor:"#f5f5f5",
        grayiconcolor:"#969696"
    },
    fonts: {
        extraLight: 'Manrope_200ExtraLight',
        light: 'Manrope_300Light',
        regular: 'Manrope_400Regular',
        medium: 'Manrope_500Medium',
        semiBold: 'Manrope_600SemiBold',
        bold: 'Manrope_700Bold',
        extraBold: 'Manrope_800ExtraBold',
    },
}